version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todos
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # backend:
  #   build: .
  #   container_name: backend
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:mypassword@db:5432/todo"

volumes:
  db_data:
